maniahandconverter/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hh/(?P<pk>\d+)/$', views.get_hh, name='get-hh'),
    url(r'^obj/(?P<pk>\d+)/$', views.get_hh_obj, name='get-hh-obj'),
    url(r'^new/(?P<pk>\d+)/$', views.get_new_hh, name='get-new-hh'),
    url(r'^history/$', views.HistoryView.as_view(), name='hh-list'),
    url(r'^history/(?P<pk>\d+)/$', views.HistoryDetailView.as_view(), name='history-detail'),
    url(r'^upload/$', views.FileUploadView.as_view(), name='file-upload'),
    url(r'^sign_s3/$', views.sign_s3, name='sign-s3'),
    url(r'^non_mavens_converter', views.NonMavensConverter.as_view(), name='non-mavens-converter'),
    url(r'^unsaved.html', views.unsaved, name='unsaved'),
]

mhc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('maniahandconverter.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maniahandconverter/models.py
from django.db import models
from mhc.storage_backend import JsonStorage, ConvertedStorage
from django.contrib.auth.models import User

class HHManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)

class HH(models.Model):
    user         = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name         = models.CharField(max_length=120, null=True, blank=True)
    file_type    = models.CharField(max_length=120, null=True, blank=True)
    path         = models.CharField(max_length=127, blank=True, null=True)
    size         = models.BigIntegerField(default=0)
    uploaded     = models.BooleanField(default=False)
    active       = models.BooleanField(default=True)
    uploaded_at  = models.DateTimeField(auto_now_add=True)
    active_items = HHManager()

    class Meta:
        ordering = ["-uploaded_at"]

    def __str__(self):
        return self.name

class HHJson(models.Model):
    hh          = models.ForeignKey('HH', null=True, on_delete=models.SET_NULL)
    file        = models.FileField(storage=JsonStorage())
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-uploaded_at"]

    def __str__(self):
        return self.file.name

class Player(models.Model):
    name        = models.CharField(max_length=63)

    def __str__(self):
        return self.name

class Game(models.Model):
    name        = models.CharField(max_length=63)

    def __str__(self):
        return self.name

class HHJson_Player(models.Model):
    hh_json     = models.ForeignKey('HHJson', null=True, on_delete=models.SET_NULL)
    player      = models.ForeignKey('Player', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return '{} | {}'.format(self.player, self.hh_json)

class HHJson_Player_Game(models.Model):
    hh_json_player   = models.ForeignKey('HHJson_Player', null=True, on_delete=models.SET_NULL)
    game             = models.ForeignKey('Game', null=True, on_delete=models.SET_NULL)
    amount           = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    count            = models.IntegerField(default=0)
    sit              = models.IntegerField(default=0)

class HHNew(models.Model):
    hh_json     = models.ForeignKey('HHJson', null=True, on_delete=models.SET_NULL)
    file        = models.FileField(storage=ConvertedStorage())
    hero        = models.CharField(max_length=63)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

maniahandconverter/controllers.py
from django.conf import settings
from django.core.files.storage import default_storage
from django.shortcuts import get_object_or_404

from .converter import hh_to_object
from .converters import create_new_hh_text, create_hh_details
from .models import (
    HH,
    Player,
    Game,
    HHJson_Player,
    HHJson_Player_Game,
    HHJson,
    HHNew
)

import json, boto3, uuid, magic

HH_LOCATION = settings.AWS_HH_LOCATION
S3_BUCKET = settings.AWS_STORAGE_BUCKET_NAME
S3_DOMAIN = settings.AWS_S3_CUSTOM_DOMAIN

def handle_get_hh(hh_json_id, user):
    if not bool(hh_json_id):
        return {'is_valid':False, 'message':'Invalid Operation'}
    hh_json = get_object_or_404(HHJson, id=hh_json_id)
    get_object_or_404(HH, id=hh_json.hh.id,user=user)
    return get_hh_text_from_s3(hh_json.hh.path)

def handle_get_new_hh(new_hh_id,user):
    if not bool(new_hh_id):
        return {'is_valid':False, 'message':'Invalid Operation'}
    new_hh = get_object_or_404(HHNew, id=new_hh_id)
    get_object_or_404(HH, id=new_hh.hh_json.hh.id,user=user)
    new_hh = HHNew.objects.get(id=new_hh_id)
    return new_hh.file.read()

def handle_get_hh_obj(hh_json_id,user):
    if not bool(hh_json_id):
        return {'is_valid':False, 'message':'Invalid Operation'}
    hh_json = get_object_or_404(HHJson, id=hh_json_id)
    get_object_or_404(HH, id=hh_json.hh.id,user=user)
    hh_obj = parse_hh_json(hh_json.file)
    return create_hh_details(hh_obj)

def handle_create_new_hh(hero_id,user):
    if not bool(hero_id):
        return {'is_valid':False, 'message':'Invalid Operation'}
    hh_json_player = get_object_or_404(HHJson_Player, id=hero_id)
    hero = hh_json_player.player.name
    hh_json = hh_json_player.hh_json
    get_object_or_404(HH, id=hh_json.hh.id,user=user)

    if HHNew.objects.filter(hero=hero, hh_json=hh_json).exists():
        return { 'is_valid': False }
    else:
        return handle_create_more_new_hh(hh_json.id, hero,user)

def handle_delete(hh_json_id,user):
    if not bool(hh_json_id):
        return {'is_valid':False, 'message':'Invalid Operation'}
    hh_json = get_object_or_404(HHJson, id=hh_json_id)
    get_object_or_404(HH, id=hh_json.hh.id,user=user)
    hh_json.hh.active = False
    hh_json.hh.save()
    return {
        'is_valid': True
    }

def handle_sign_s3(file_name, file_type, file_size, ext, user):
    if ext != '.txt':
        return {'is_valid': False,'message': 'Not a .txt file'}

    if int(file_size) > 1999000:
        return {'is_valid': False, 'message': 'File must be under 2MB'}

    hh              = create_hh_model(file_name, file_type, file_size, ext, user)
    presigned_post  = create_s3_signature(hh.path, file_type)
    return {
        'is_valid': True,
        'data': presigned_post,
        'hh_id': hh.id,
        'url': '{}/{}'.format(S3_DOMAIN, hh.path)
    }

def handle_create_hh_json(hh_id, key, user):
    if not bool(hh_id) or not bool(key):
        return {'is_valid':False, 'message':'Invalid Operation'}

    hh      = update_hh_model(hh_id, user)
    hh_text = get_hh_text_from_s3(key)

    if hh_text == '':
        return {'is_valid':False, 'message': 'You trying to hack me?'}

    hh_obj  = hh_to_object.init(hh_text)
    hh_json = create_hh_json_model(hh_obj, hh, user)
    return {
        'is_valid': True,
        'hh_json_id': hh_json.id,
    }

def handle_create_all_models(hh_json_id,user):
    if not bool(hh_json_id):
        return {'is_valid':False, 'message':'Invalid Operation'}
    hh_json = get_object_or_404(HHJson,id=hh_json_id)
    get_object_or_404(HH,id=hh_json.hh.id,user=user)
    hh_obj  = parse_hh_json(hh_json.file)
    create_rest_of_models(hh_json, hh_obj)
    return {
        'is_valid': True,
        'players': hh_obj['players']
    }

def handle_create_more_new_hh(hh_json_id, hero, user):
    if not bool(hh_json_id) or not bool(hero):
        return {'is_valid':False, 'message':'Invalid Operation'}
    hh_json = get_object_or_404(HHJson, id=hh_json_id)
    get_object_or_404(HH, id=hh_json.hh.id, user=user)
    new_hh = create_new_hh_model(hh_json, hero, user)
    return {
        'is_valid': True,
        'hero': hero,
        'new_hh_id': new_hh.id
    }

#############################
##### S3 HELPER METHODS #####
#############################

def create_s3_signature(hh_path, file_type):
    s3 = boto3.client('s3')
    return s3.generate_presigned_post(
        Bucket = S3_BUCKET,
        Key = hh_path,
        Fields = {"acl": "private", "Content-Type": file_type},
        Conditions = [
            {"acl": "private"},
            {"Content-Type": file_type}
        ],
        ExpiresIn = 3600
    )

def get_hh_text_from_s3(key):
    s3 = boto3.resource('s3')
    hh_s3 = s3.Object(S3_BUCKET, key)
    text = hh_s3.get()['Body'].read()

    if magic.from_buffer(text,mime=True) != 'text/plain':
        return ''

    hh_text = text.decode('utf-8', 'ignore')
    return hh_text

################################
##### Model HELPER METHODS #####
################################

# hh.path is (:path)/(:id).txt
def create_hh_model(file_name, file_type, file_size, ext, user):
    hh = HH.active_items.create(name=file_name, file_type=file_type, size=file_size, user=user)
    hh.save()
    hh.path = "{}/{}/{}".format(HH_LOCATION, user, str(uuid.uuid1()), ext)
    hh.save()
    return hh

def update_hh_model(hh_id,user):
    hh = get_object_or_404(HH, id=hh_id,user=user)
    hh.uploaded = True
    hh.save()
    return hh

def create_hh_json_model(hh_obj, hh, user):
    json_text = json.dumps(hh_obj)
    file_name = "{}/{}.txt".format(user,str(uuid.uuid1()))

    file = default_storage.open(file_name, 'w')
    file.write(json_text)

    hh_json = HHJson(hh=hh, file=file)
    hh_json.save()
    return hh_json

def create_rest_of_models(hh_json, hh_obj):
    hh = hh_json.hh
    games = {}
    players = {}

    for g in hh_obj['games']:
        game, created = Game.objects.get_or_create(name=g)
        game.save()
        if game.name not in games:
            games[game.name] = game

    for p in hh_obj['players']:
        player, created = Player.objects.get_or_create(name=p)
        player.save()
        if player.name not in players:
            players[player.name] = player

    for p in players:
        hh_json_player = HHJson_Player(hh_json=hh_json, player=players[p])
        hh_json_player.save()

        for g in hh_obj['players'][p]['games']:
            amount = hh_obj['players'][p]['games'][g]['amount']
            count = hh_obj['players'][p]['games'][g]['count']
            sit = hh_obj['players'][p]['games'][g]['sit']
            hh_json_player_game = HHJson_Player_Game(
                hh_json_player=hh_json_player,
                game=games[g],
                amount=amount,
                count=count,
                sit=sit
            )
            hh_json_player_game.save()

def create_new_hh_model(hh_json, hero,user):
    hh_obj = parse_hh_json(hh_json.file)
    new_hh_text = create_new_hh_text(hh_obj, hero)
    file_name = "{}/{}.txt".format(user, str(uuid.uuid1()))

    file = default_storage.open(file_name, 'w')
    file.write(new_hh_text)

    new_hh = HHNew(hh_json=hh_json, file=file, hero=hero)
    new_hh.save()
    return new_hh

################################
##### Other HELPER METHODS #####
################################

def parse_hh_json(file):
    byte_text = file.read()
    string = byte_text.decode('utf-8')
    hh_obj = json.loads(string)
    return hh_obj

maniahandconverter/views.py
from django.shortcuts import render
from django.views import View, generic
from django.http import JsonResponse, HttpResponse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import HH, HHJson, HHNew
from .controllers import (
    handle_get_hh,
    handle_get_new_hh,
    handle_get_hh_obj,
    handle_create_new_hh,
    handle_delete,
    handle_sign_s3,
    handle_create_hh_json,
    handle_create_all_models,
    handle_create_more_new_hh,
)

import os

def index(request):
    return render(request,'index.html',context={})

@login_required
def get_hh(request, **kwargs):
    return HttpResponse(handle_get_hh(kwargs['pk'], request.user), content_type='text/plain')

@login_required
def get_new_hh(request, **kwargs):
    return HttpResponse(handle_get_new_hh(kwargs['pk'],request.user), content_type='text/plain')

@login_required
def get_hh_obj(request, **kwargs):
    return HttpResponse(handle_get_hh_obj(kwargs['pk'],request.user), content_type='text/plain')

class HistoryView(LoginRequiredMixin, generic.ListView):
    model = HHJson
    paginate_by = 20
    template_name = 'history.html'

    def get_queryset(self):
        return HHJson.objects.filter(hh__active=True,hh__user=self.request.user)

class HistoryDetailView(LoginRequiredMixin, generic.DetailView):
    model = HHJson
    template_name = 'history_detail.html'

    def post(self, reqeust, **kwargs):
        hero_id = self.request.POST.get('hero_id')
        data = handle_create_new_hh(hero_id,self.request.user)
        return JsonResponse(data)

    def put(self, request, **kwargs):
        return JsonResponse(handle_delete(kwargs['pk'], self.request.user))

    def get_queryset(self):
        return HHJson.objects.filter(hh__active=True,hh__user=self.request.user)

# after User clicks upload, hh model is created, and
#   - path is local/unconverted in production, and
#   - path is media/unconverted in deployment
# returns the signature to upload to s3
def sign_s3(request, **kwargs):
    if not request.user.is_authenticated:
        return HttpResponse(status=403)

    file_name       = request.GET.get('file_name')
    file_type       = request.GET.get('file_type')
    file_size       = request.GET.get('file_size')
    file_path, ext  = os.path.splitext(file_name)
    return JsonResponse(handle_sign_s3(file_name, file_type, file_size, ext, request.user))

class FileUploadView(LoginRequiredMixin, View):
    def get(self, request):
        return render(self.request, 'upload.html')

    def post(self, request):
        post_type   = self.request.POST.get('type')

        # After file is uploaded to s3,
        #   1. hh model is updated to uploaded
        #   2. hhjson is created
        #      - file is stored on s3
        #      - file contains ... write stuff here ...
        # returns hh_json_id
        if post_type == "sync1":
            hh_id       = self.request.POST.get('hh_id')
            key         = self.request.POST.get('key')
            data        = handle_create_hh_json(hh_id, key, request.user)
        # After hh object is saved, models are created:
        #   1. player models
        #   2. game models
        #   3. hhjson_player models
        #   4. hhjson_player_game models
        elif post_type == "sync2":
            hh_json_id  = self.request.POST.get('hh_json_id')
            data        = handle_create_all_models(hh_json_id,request.user)

        # If all goes well, user ships in a hero parameter,
        #   then a converted file is created
        # returns a link to the converted file
        elif post_type == "convert":
            hh_json_id  = self.request.POST.get('hh_json_id')
            hero        = self.request.POST.get('hero')
            data        = handle_create_more_new_hh(hh_json_id, hero, request.user)

        return JsonResponse(data)

class NonMavensConverter(LoginRequiredMixin, View):
    def get(self, request):
        return render(self.request, 'nonmavens.html')

    # def post(self, request):
    #     return JsonResponse({})

def unsaved(request, **kwargs):
    return HttpResponse(200);

maniahandconverter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% block javascript %}{% endblock %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'file-upload' %}">Upload HHs</a></li>
          <li><a href="{% url 'hh-list' %}">History</a></li>
      </ul>
     {% endblock %}
    </div>

    <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
    </div>

  </div>
</div>
</body>
</html>

maniahandconverter/templates/history.html
{% extends 'base.html' %}

{% block title %}<title>History</title>{% endblock %}

{% block content %}
<h2>History</h2>

<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Upload Date</th>
      <th scope="col">Original Hand History</th>
      <th scope="col">
        <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
      </th>
    </tr>
  </thead>
  <tbody>
    {% for hhjson in hhjson_list %}
    <tr>
      <td>{{ hhjson.uploaded_at }}</td>
      <td><a href="{% url 'get-hh' hhjson.id %}" target="_blank">{{ hhjson.hh.name }}</a></td>
      <td>
        <a href="{% url 'history-detail' hhjson.id %}">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

maniahandconverter/templates/history_detail.html
{% extends 'base.html' %}

{% block title %}<title>HH Details</title>{% endblock %}

{% block javascript %}
<meta name="csrf-token" content="{{csrf_token}}">
<meta name="hhjson-id" content="{{hhjson.id}}">
{% load static %}
<script src="{% static 'js/history_detail.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/history_detail.css' %}">
{% endblock %}


{% block content %}
<h2>{{hhjson.hh}} <button class="delete-all btn btn-danger">Delete</a></button></h2>

<div class="history-detail-original">
  <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
  <ul class="history-detail-list">
    <li><a href="{% url 'get-hh' hhjson.id %}" target="_blank"><span>Original File</span></a></li>
    <li><a href="{% url 'get-hh-obj' hhjson.id %}" target="_blank"><span>File Details</span></a></li>
  </ul>
</div>

<div class="history-detail-converted">
  <h4>Converted Files</h4>
  <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
  <ul class="history-detail-list converted-file-list">
    {% for new_hh in hhjson.hhnew_set.all %}
    <li>
      <a href="{% url 'get-new-hh' new_hh.id %}" target="_blank">{{new_hh.hero}}</a>
    </li>
    {% endfor %}
    </div>
  </ul>
  <div class="create-form">
    <form>
      <select>
        {% for hh_player in hhjson.hhjson_player_set.all %}
        <option value="{{hh_player.id}}">{{hh_player.player.name}}</option>
        {% endfor %}
      </select>
      <button class="btn btn-primary btn-sm add-button">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      </button>
    </form>
    <div id="message"></div>
</div>

<div class="history-detail-stats">
  <h4>Statistics</h4>
  <div class="container">
      {% for hh_player in hhjson.hhjson_player_set.all %}
      <div class="row head-row">
        <div class="col-sm-3"><b>{{hh_player.player.name}}</b></div>
        <div class="col-sm-1"><b>Hands</b></div>
        <div class="col-sm-1"><b>Sitout</b></div>
        <div class="col-sm-1"><b>Won ($)</b></div>
      </div>
      {% for hh_player_game in hh_player.hhjson_player_game_set.all %}
      <div class="row body-row">
        <div class="col-sm-3">{{hh_player_game.game.name}}</div>
        <div class="col-sm-1">{{hh_player_game.count}}</div>
        <div class="col-sm-1">{{hh_player_game.sit}}</div>
        <div class="col-sm-3">{{hh_player_game.amount|floatformat:"2"}}</div>
      </div>
      {% endfor %}
      {% endfor %}

  </div>
</div>
{% endblock %}

maniahandconverter/templates/index.html
{% extends 'base.html' %}

{% block title %}<title>Handconverter</title>{% endblock %}

{% block content %}
<h2>Welcome!</h2>
<hr>
<h4>Supported Games:</h4>
<ul>
  <li>Limit Hold'em</li>
  <li>Limit Omaha</li>
  <li>Limit Omaha Hi-Lo</li>
  <li>NL Hold'em</li>
  <li>PL Omaha</li>
  <li>PL Omaha Hi-Lo</li>
</ul>
<hr>
<span>Please don't try to break the site.</span><br>
<span>Also, the converter will only work on poker mania hands in its exact format.</span><br>
<span>If you choose to upload anything bizzaire, unexpected results may occur.</span><br>
<span>Also please report any bugs</span>
{% endblock %}

maniahandconverter/templates/nonmavens.html
{% extends 'base.html' %}

{% block title %}<title>Non Mavens Converter</title>{% endblock %}

{% block javascript %}
  <meta name="csrf-token" content="{{csrf_token}}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/vendor/jquery.ui.widget.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/jquery.fileupload.min.js"></script>
  {% load static %}
  <script src="{% static 'js/nonmavens.js' %}"></script>
{% endblock %}

{% block content %}
<h2>Non Mavens Converter</h2>

<button type="button" class="btn btn-primary js-upload-hhs">
  <span class="glyphicon glyphicon-cloud-upload"></span>
  <span>Select Single HH File</span>
</button>

<input id="fileupload" type="file" name="file" style="display: none;">

<div class="table selected-hhs-wrapper">
  <h4>Selected Hand Histories</h4>
  <div class="selected-hh">
  </div>
</div>
{% endblock %}

maniahandconverter/templates/upload.html
{% extends 'base.html' %}

{% block title %}<title>Upload HHs</title>{% endblock %}

{% block javascript %}
  <meta name="csrf-token" content="{{csrf_token}}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/vendor/jquery.ui.widget.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.2/js/jquery.fileupload.min.js"></script>
  {% load static %}
  <script src="{% static 'js/upload.js' %}"></script>
{% endblock %}

{% block content %}
<h2>Upload HHs</h2>

<button type="button" class="btn btn-primary js-upload-hhs">
  <span class="glyphicon glyphicon-cloud-upload"></span>
  <span>Select HHs</span>
</button>

<input id="fileupload" type="file" name="file" multiple style="display: none;">

<div class="table selected-hhs-wrapper">
  <h4>Selected Hand Histories</h4>
  <div class="selected-hh">
  </div>
</div>
{% endblock %}